### ISSUE TITLE
Hyphen in json key

### ISSUE THREAD

**Issue by dfkki123508** [evinism/mistql#109]
I'm trying to do this
```
{
    "key-with-hyphens": "a match"
} | key-with-hyphens =~ (regex "a match")
```
How can get the value of a json key with hyphens inside? Thanks!

**Comment by evinism** [comment]
You can do indexing on the `@` operator to access names that can't be accessed as identifiers, for example`@["key-with-hyphens"]`.

The code you've got above should look like: `{ "key-with-hyphens": "a match" } | apply @["key-with-hyphens"] =~ (regex "a match")`

Note the use of the `apply` function here. The pipe operator in mistql (in contrast to other similar languages) expects that we're passing the result of the previous expression as the last argument to a function, e.g. `count somearr` becomes `somearr | count` rather than `somearr | count @`.

**Comment by evinism** [comment]
Part of me is wondering whether to introduce a new bit of syntax, namely `|>` as syntactic sugar for using `apply`, such that you could write `{"key-with-hyphens": "a match"} |> @["key-with-hyphens"] =~ (regex "a match")`

I'm always hesitant to add new syntax, as i feel like simple syntax but a broad library is what makes MistQL MistQL.

**Comment by evinism** [comment]
Closing for now. Will reopen if this answer is not satisfactory.

**Comment by dfkki123508** [comment]
I see. Thank you for the quick explanation!!
