### ISSUE TITLE
Intentionally not turing complete?

### ISSUE THREAD

**Issue by cfilipov** [evinism/mistql#47]
I don't see this explicitly mentioned in the docs but it seems this is not turing complete (which I think is a good thing). I wonder if this is an intentional design decision and if the plan is to keep it this way.

**Comment by evinism** [comment]
I don't mention it in the docs, but yes, this is intentional -- as you say, it isn't Turing complete. My plan was to start with a total language, and introduce features that would make it Turing complete only under the circumstances that there was a strong use case that I wasn't capturing.

My guess is that almost all use cases can be captured with provably terminating statements.

**Comment by evinism** [comment]
i'll reopen if that answer isn't satisfied, but until then, i'll close it.
